cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00000220.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00000333.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00000752.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00001009.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00001397.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00001646.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00001647.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00002070.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00002483.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00002789.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00002996.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00003194.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00003461.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00004267.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00005017.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00005604.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00006021.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00006129.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00006364.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00007260.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00007928.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00008585.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00009159.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00009633.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00009948.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00010304.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00010846.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00011023.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00011495.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00011604.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00012340.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00012424.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00012498.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00012792.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00012974.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00013067.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00013278.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00013622.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00013653.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00013670.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00013869.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00014022.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00014500.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00014584.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00015124.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00015166.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00015395.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00015419.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00015420.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00015786.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00016039.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00016461.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00017188.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00017212.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00017938.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00017965.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00018423.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00019146.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00019464.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00019986.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00022325.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00023129.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00023210.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00023543.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00024008.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00024175.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00024240.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00024249.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00024642.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00025344.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00025501.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00026458.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00026486.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00026824.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00027414.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00027429.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00027836.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00028408.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00028480.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00028596.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00028634.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00028837.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00028895.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00028983.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00029124.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00029246.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00030603.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00030606.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00030688.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00030877.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00031219.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00032022.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00032117.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00032157.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00033463.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00033660.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00033673.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00033806.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00033851.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00034261.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00034267.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00034575.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00034628.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00034813.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00034938.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00035101.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00035118.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00035344.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00035356.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00035763.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00036072.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00036649.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00036934.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00037130.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00037435.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00037475.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00037877.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00037886.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00038282.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00038637.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00038904.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00038914.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00039291.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00039586.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00040834.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00041989.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00042040.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00042286.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00042330.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00042767.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00042922.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00043714.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00043817.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00043935.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00044212.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00044450.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00044735.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00045135.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00045204.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00045964.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00046804.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00047017.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00047305.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00047583.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/pug/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00047992.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00048670.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/zebra/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00048753.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00049039.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00049284.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
cp -as /data/xiaozhou/Downloads/datasets/imagenet/imagenet12-val/ILSVRC2012_val_00049729.JPEG /data/xiaozhou/Downloads/datasets/imagenet/testimages/horse_cart/
